"""Render LIVE_TRADING_CASE_STUDY.md from computed positions and summary.

No number in the document is typed by hand: every figure is formatted from the
`summary` dict or the position rows produced by `live.report.compute`.
"""

from __future__ import annotations

import math
from decimal import ROUND_HALF_UP, Decimal

from live.analytics import SIZE_ORDER
from live.ledger import OPEN, SETTLED

CENT = Decimal("0.01")


# ------------------------------------------------------------------ format
def usd(x, sign: bool = False) -> str:
    if x is None:
        return "n/a"
    d = Decimal(str(x)).quantize(CENT, rounding=ROUND_HALF_UP)
    body = f"${abs(d):,.2f}"
    if d < 0:
        return f"−{body}"
    return f"+{body}" if sign and d > 0 else body


def pct(x, digits: int = 1, sign: bool = True) -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    v = float(x) * 100
    s = f"{v:+.{digits}f}%" if sign else f"{v:.{digits}f}%"
    return s.replace("-", "−")


def pts(x, digits: int = 1) -> str:
    """Probability difference in percentage points (no negative zero).

    >>> pts(-0.0000282, 2), pts(0.0123)
    ('0.00 pp', '+1.2 pp')
    """
    if x is None:
        return "n/a"
    v = round(float(x) * 100, digits)
    if v == 0:
        return f"{0:.{digits}f} pp"
    return f"{v:+.{digits}f} pp".replace("-", "−")


def ci(d: dict, fmt=pct) -> str:
    if not d or d.get("lo") is None or math.isnan(d["lo"]):
        return "n/a"
    return f"[{fmt(d['lo'])}, {fmt(d['hi'])}]"


def day(ts: str | None) -> str:
    return ts[:10] if ts else ""


def minute(ts: str | None) -> str:
    return f"{ts[:16].replace('T', ' ')}" if ts else ""


def num(x, digits: int = 2) -> str:
    if x is None or x == "":
        return ""
    d = Decimal(str(x))
    return f"{d:.{digits}f}"


def table(head: list[str], rows: list[list], align: str | None = None) -> str:
    align = align or "l" + "r" * (len(head) - 1)
    sep = ["---:" if a == "r" else "---" for a in align]
    lines = ["| " + " | ".join(head) + " |", "| " + " | ".join(sep) + " |"]
    lines += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def group_rows(groups: list[dict], order: list[str] | None = None) -> list[list]:
    if order:
        groups = sorted(
            groups, key=lambda g: order.index(g["group"]) if g["group"] in order else 99
        )
    out = []
    for g in groups:
        held = g["held"]
        out.append(
            [
                g["group"],
                g["n"],
                f"{g['wins'] / g['n']:.0%}",
                usd(g["capital"]),
                usd(g["pnl"], sign=True),
                pct(g["roi"]),
                usd(g["fees"]),
                f"{g['held_won']:.0f} / {g['held_implied']:.1f}" if held else "—",
            ]
        )
    return out


GROUP_HEAD = [
    "", "Closed", "P&L > 0", "Capital at risk", "P&L", "ROI", "Fees", "Held: won / price-implied",
]  # fmt: skip


# ------------------------------------------------------------------ render
def render(rows: list[dict], s: dict) -> str:
    m, c, h, cl, dd, ck = (
        s["manifest"], s["counts"], s["held"], s["clv"], s["drawdown"], s["checks"]
    )  # fmt: skip
    by_id = {r["position_id"]: r for r in rows}
    conc = s["concentration"]
    g = s["groups"]
    exited = next(x for x in g["exit"] if x["group"] == "sold before settlement")
    held_g = next(x for x in g["exit"] if x["group"] == "held to settlement")
    top2_share = conc["top2_pnl"] / s["realized_pnl"] if s["realized_pnl"] else None
    credits = m["non_trading_credits_usd"]
    out: list[str] = []
    w = out.append

    w("# Live Trading Case Study: Polymarket US sports contracts, January–September 2026\n")
    w(
        f"> **Real-capital trading.** One personal account on Polymarket US, "
        f"{c['fills']} fills in {c['positions']} positions, first fill "
        f"{day(s['first_entry'])}, last fill {day(s['last_fill'])}, account history pulled "
        f"{m['pulled_at_utc_date']}. Generated by `uv run -m live.report` from the sanitized "
        f"records in [`data/live/`](data/live/); no figure below is typed by hand, and the "
        f"report refuses to build unless the ledger reconciles to the fills exactly.\n"
    )

    # ---------------------------------------------------------------- summary
    w("## Summary\n")
    roi_ci = s["roi_ci_day"]
    edge_shown = roi_ci["lo"] > 0
    w(
        f"- **Result.** {usd(s['realized_pnl'], True)} realized on {c['closed']} closed "
        f"positions and {usd(s['capital_at_risk_closed'])} of capital at risk, after "
        f"{usd(s['fees_closed'])} of fees: **ROI {pct(s['roi'])}, 95% CI {ci(roi_ci)}** "
        f"(bootstrap over {roi_ci['n_clusters']} settlement days). "
        + (
            "The interval excludes zero."
            if edge_shown
            else "The interval includes zero. This record does not show an edge."
        )
    )
    excess_zero = h["excess"]["lo"] <= 0 <= h["excess"]["hi"]
    w(
        f"- **The {s['win_rate']['rate']:.1%} win rate "
        + ("is explained by price.** " if excess_zero else "differs from what price implied.** ")
        + f"On the {h['n']} positions held to settlement, entry prices implied "
        f"{h['implied']:.1f} wins and {h['won']:.0f} occurred. Excess win rate "
        f"{pts(h['excess']['point'])}, 95% CI {ci(h['excess'], pts)}. Buying favourites "
        "produces a high win rate by construction."
    )
    w(
        f"- **Concentrated.** Two positions produced {usd(conc['top2_pnl'], True)} of the "
        f"{usd(s['realized_pnl'], True)} ({top2_share:.0%}). The other {c['closed'] - 2} "
        f"returned {usd(conc['rest_pnl'], True)} ({pct(conc['rest_roi'])})."
    )
    w(
        f"- **Drawdown.** Cumulative realized P&L peaked at {usd(dd['peak'], True)} on "
        f"{day(dd['peak_at'])} and fell {usd(dd['max_drawdown'])} by {day(dd['trough_at'])}."
    )
    if cl["n"]:
        verdict = (
            "Beat the close"
            if cl["mean"]["lo"] > 0
            else "Lost to the close"
            if cl["mean"]["hi"] < 0
            else "No evidence of beating the close"
        )
        w(
            f"- **{verdict}.** On the {cl['n']} pregame positions where a "
            f"closing price could be validated, mean closing-line value was "
            f"{pts(cl['mean']['point'])} (95% CI {ci(cl['mean'], pts)}), positive on "
            f"{cl['share_positive']:.0%}. The benchmark is a cross-venue proxy; see "
            f"[CLV](#closing-line-value-cross-venue-proxy)."
        )
    w(
        f"- **Exits versus holds.** {exited['n']} positions sold before settlement returned "
        f"{usd(exited['pnl'], True)} ({pct(exited['roi'])}); positions held to settlement "
        f"returned {usd(held_g['pnl'], True)} ({pct(held_g['roi'])}, 95% CI "
        f"{ci(h['roi_ci_day'])}). Selection is a likely part of this, since losing positions "
        "are the ones a trader is tempted to cut."
    )
    gaps = len(ck["volume_gaps"])
    w(
        "- **Accounting is exact and checked against the exchange.** Every fill's cash flow "
        f"matches the exchange's own trade cost ({ck['fill_cost_match']}/{ck['fills']}), and "
        f"net shares at settlement match the exchange's position record "
        f"({ck['settled_qty_match']}/{ck['settled_markets']}). "
        + (
            f"The {gaps} markets where the exchange's position counters show executions "
            "missing from its activity feed are listed in "
            "[Integrity checks](#integrity-checks), with their bounded P&L effect.\n"
            if gaps
            else "Gross volume matches the exchange's counters in every settled market.\n"
        )
    )
    if not edge_shown:
        w(
            "What this shows is the evaluation process, not alpha. It is a real record, "
            "accounted to the fraction of a cent and read with price context, clustering and "
            'concentration in view, and it reports "no demonstrated edge" because that is '
            "what the evidence supports.\n"
        )

    # ---------------------------------------------------------------- scope
    w("## What kind of evidence this is\n")
    w(
        table(
            ["Category", "What", "Where"],
            [
                [
                    "**Real-capital trading**",
                    "This document: every fill and settlement on one live Polymarket US account",
                    "`live/`, `data/live/`, this file",
                ],
                [
                    "Historical reconstruction",
                    "An earlier analysis of the *same account* from a scraped UI export "
                    "(relative dates, no prices or fees). Superseded by this document "
                    "where they differ; see [below](#relation-to-the-earlier-write-up)",
                    "[polymarket-vegas-edge](https://github.com/crollila/polymarket-vegas-edge) research note",
                ],
                [
                    "Research / backtest",
                    "Polymarket vs Kalshi calibration on backfilled prices. No trades; the "
                    "cost-modelled backtest deliberately did not run",
                    "this repository's [README](README.md)",
                ],
                [
                    "Paper / simulated",
                    "Model picks logged with `paper: true`; agent trading competitions on paper "
                    "accounts. None of it is counted here",
                    "polymarket-vegas-edge `predictions.jsonl`; "
                    "[exalted-agent-trading-lab](https://github.com/crollila/exalted-agent-trading-lab)",
                ],
            ],
            "lll",
        )
    )
    w(
        "\nNo model probability was stored at order time for any of these trades (the only "
        "logged model picks are paper-flagged and match no real fill), and no "
        "contemporaneous thesis was recorded. Those fields are reported as unavailable "
        "rather than reconstructed.\n"
    )

    # ---------------------------------------------------------------- data
    w("## Data and method\n")
    acts = ", ".join(f"{k.lower().replace('_', ' ')} {v}" for k, v in m["activity_counts"].items())
    w(
        f"**Source.** {m['source']}. Pulled {m['pulled_at_utc_date']}; activity records: "
        f"{acts}. SHA-256 of the private raw file: `{m['raw_sha256'][:16]}…` (recorded in "
        f"[`manifest.json`](data/live/manifest.json) so a future pull can be told apart).\n"
    )
    w(
        "```\n"
        "raw account JSON (private, never committed)\n"
        "   └─ live/ingest.py    drop exchange ids, counterparty orders, cash-movement detail;\n"
        "                        salted-HMAC stable ids  ──►  data/live/{fills,markets,settlements}.csv\n"
        "public price history\n"
        "   └─ live/reference.py scheduled starts + last pre-start print  ──►  data/live/event_reference.csv\n"
        "data/live/*.csv\n"
        "   └─ live/report.py    exact Decimal ledger, reconciliation asserts, statistics\n"
        "                        ──►  data/live/positions.csv, data/live/summary.json, this file\n"
        "```\n"
    )
    w("**Ledger conventions**, each verified on the raw records rather than assumed:\n")
    w(
        f"1. A fill's price is the YES price even on NO orders, so a NO share costs `1 − px`. "
        f"With that reading, buy cash `= qty × price + fee` and sell cash `= qty × price − fee` "
        f"equal the exchange's own `trade.cost` on {ck['fill_cost_match']} of {ck['fills']} fills.\n"
        f"2. Each settled share pays its side's settlement price (1 or 0; 0.5 on a void).\n"
        f"3. A **position** is one (market, side). {c['positions'] - c['markets']} markets were "
        f"traded on both sides at different times; those are separate bets.\n"
        f"4. **Capital at risk** is all cash committed to a position, buys plus their fees. "
        f"**ROI** is realized P&L over capital at risk, summed over closed positions. Capital "
        f"was recycled, so {usd(s['capital_at_risk_closed'])} is turnover, not account size; "
        f"deposits are not in this data, so no return on account equity is reported.\n"
        f"5. **Realized P&L** counts only closed positions: settled, or fully sold. The "
        f"{c['open']} positions open at the pull ({usd(s['open_capital_at_risk'])} at risk) "
        f"are excluded, not marked.\n"
        f"6. **Confidence intervals** are percentile bootstraps (10,000 draws, fixed seed) "
        f"resampling whole settlement days, because same-day sports outcomes and same-day "
        f"sizing decisions are correlated. Position-level resampling gives "
        f"{ci(s['roi_ci_iid'])} for ROI, slightly narrower than the clustered interval.\n"
        f"7. **Excluded as non-trading:** referral credits ({usd(credits.get('REFERRAL_BONUS'))}), "
        f'two exchange-initiated balance credits labelled "System Issue" and "Balance '
        f'reconciliation adjustment" ({usd(credits.get("TRANSFER"))} total), and withdrawals '
        f"(count only).\n"
    )

    # ---------------------------------------------------------------- fields
    w("## Field availability\n")
    n_start = sum(1 for r in rows if r["event_start_utc"])
    w(
        table(
            ["Field", "Status", "Source or reason"],
            [
                ["Market, market slug", "available", "exchange order metadata"],
                ["UTC entry timestamp", "available", "first buy fill, microsecond precision"],
                ["Side, outcome backed", "available", "order `outcomeSide` + outcome label"],
                ["Entry price", "available", "volume-weighted buy price, before fees"],
                ["Quantity, fills, orders", "available", "per fill; ids replaced by salted HMACs"],
                ["Capital at risk", "available", "buys + buy fees"],
                [
                    "Order type",
                    "available",
                    "LIMIT on every fill; time-in-force kept; all fills were taker (aggressor)",
                ],
                ["Fees", "available", "per-fill exchange commission"],
                ["Exit / settlement price", "available", "sell VWAP; exchange settlement price"],
                ["Realized P&L, return", "available", "computed; reconciled to fills"],
                [
                    "Market probability at entry",
                    "available",
                    "the entry price itself (an executable price, so it includes the spread)",
                ],
                [
                    "Event start, entry timing",
                    f"{n_start} of {len(rows)}",
                    "exchange (combos) or public price history (singles)",
                ],
                [
                    "Closing-line value",
                    f"{cl['n']} of {len(rows)}",
                    "pregame singles with a validated cross-venue close only",
                ],
                [
                    "Model probability",
                    "**unavailable**",
                    "never stored at order time for a real trade",
                ],
                ["Edge at entry", "**unavailable**", "requires a model probability"],
                ["Thesis", "**unavailable**", "no contemporaneous record exists"],
            ],
            "lll",
        )
    )
    w("")

    # ---------------------------------------------------------------- results
    w("## Results\n")
    wr = s["win_rate"]
    w(
        table(
            ["Metric", "Value"],
            [
                ["Fills / orders", f"{c['fills']} / {c['orders']}"],
                [
                    "Positions (closed: settled + sold, open)",
                    f"{c['positions']} ({c['settled']} + {c['exited']}, {c['open']})",
                ],
                ["Capital at risk, closed positions", usd(s["capital_at_risk_closed"])],
                ["Realized P&L", usd(s["realized_pnl"], True)],
                ["Realized P&L before fees", usd(s["gross_pnl_before_fees"], True)],
                ["ROI (95% CI, day-clustered)", f"{pct(s['roi'])} {ci(roi_ci)}"],
                [
                    "Realized P&L (95% CI, day-clustered)",
                    f"{usd(s['realized_pnl'], True)} [{usd(s['pnl_ci_day']['lo'], True)}, {usd(s['pnl_ci_day']['hi'], True)}]",
                ],
                [
                    "Win rate (Wilson 95% CI)",
                    f"{wr['rate']:.1%} [{wr['lo']:.1%}, {wr['hi']:.1%}] ({wr['wins']}/{wr['n']})",
                ],
                [
                    "Fees, all fills",
                    f"{usd(s['fees_all'])} ({pct(s['fee_pct_notional'], 2, sign=False)} of {usd(s['traded_notional'])} traded)",
                ],
                [
                    "Max drawdown, realized P&L",
                    f"{usd(dd['max_drawdown'])} ({day(dd['peak_at'])} → {day(dd['trough_at'])})",
                ],
                [
                    "Best / worst position",
                    f"{usd(by_id[conc['best5'][0]]['realized_pnl'], True)} / {usd(by_id[conc['worst5'][0]]['realized_pnl'], True)}",
                ],
            ],
            "lr",
        )
    )
    w("")

    w("### Win rate in price context\n")
    w(
        "A win rate means nothing without the prices paid. If the entry price is a fair "
        "probability, the expected number of wins is the sum of entry prices. Fees raise the "
        "bar slightly: break-even requires winning the sum of price plus fee per share.\n"
    )
    w(
        table(
            ["Held to settlement", "Value"],
            [
                ["Positions", h["n"]],
                ["Wins observed", f"{h['won']:.0f}"],
                ["Wins implied by entry prices", f"{h['implied']:.2f}"],
                ["Wins needed to break even after fees", f"{h['breakeven_with_fees']:.2f}"],
                [
                    "Excess win rate (95% CI)",
                    f"{pts(h['excess']['point'], 2)} {ci(h['excess'], pts)}",
                ],
                [
                    "Excess after fees (95% CI)",
                    f"{pts(h['excess_after_fees']['point'], 2)} {ci(h['excess_after_fees'], pts)}",
                ],
                ["Brier score of entry prices", f"{h['brier_entry_price']:.4f}"],
            ],
            "lr",
        )
    )
    w(
        "\nBy entry price (positions held to settlement only in the last column; the rest "
        "include positions sold early):\n"
    )
    w(
        table(
            GROUP_HEAD,
            group_rows(
                g["price"], ["0.00-0.20", "0.20-0.40", "0.40-0.60", "0.60-0.80", "0.80-1.00"]
            ),
        )
    )
    if h["excess"]["lo"] <= 0 <= h["excess"]["hi"]:
        w(
            f"\nCounted equally, the held positions won {h['won']:.0f} times against "
            f"{h['implied']:.1f} implied by price: no detectable selection skill. Dollars, "
            f"however, were not spread evenly. Held positions returned "
            f"{pct(held_g['roi'])} on capital, a dollar-weighted result driven by a few large "
            "positions (see sizes below), and its interval includes zero.\n"
        )

    w("### Concentration\n")
    w(
        table(
            ["", "Position", "Entry (UTC)", "Market", "Side", "Entry px", "At risk", "P&L"],
            [
                [lab, *_brief(by_id[i])]
                for lab, ids in (("best", conc["best5"]), ("worst", conc["worst5"]))
                for i in ids
            ],
            "llllrrrr",
        )
    )
    w(
        f"\nWithout the two largest winners the remaining {c['closed'] - 2} positions made "
        f"{usd(conc['rest_pnl'], True)}, ROI {pct(conc['rest_roi'], 2)}.\n"
    )

    w("### By market type\n")
    for title, key, order in [
        ("Contract type", "kind", None),
        ("League (singles; combos pooled)", "league", None),
        ("Entry timing vs scheduled start", "timing", ["pregame", "in-play", "mixed", "unknown"]),
        ("Side", "side", None),
        ("Exit", "exit", None),
    ]:
        w(f"**{title}**\n")
        w(table(GROUP_HEAD, group_rows(g[key], order)))
        w("")
    leagues = [x for x in g["league"] if x["group"] != "combo"]
    big = max(leagues, key=lambda x: x["n"])
    weak = min(leagues, key=lambda x: x["roi"])
    timing_big = max(g["timing"], key=lambda x: x["n"])
    w(
        f"The largest league segment is {big['group'].upper()} ({big['n']} positions, "
        f"{pct(big['roi'])}); the weakest by ROI is {weak['group'].upper()} "
        f"({weak['n']} positions, {pct(weak['roi'])}). The largest timing segment is "
        f"{timing_big['group']} ({timing_big['n']} positions, {pct(timing_big['roi'])}). "
        'Small segments are shown for completeness, not as findings. "Unknown" timing '
        "means the event was not in the public reference.\n"
    )

    w("### Position sizes\n")
    q = s["size_quantiles"]
    w(
        f"Capital at risk per position: min {usd(q['min'])}, 25th pct {usd(q['p25'])}, "
        f"median {usd(q['median'])}, 75th pct {usd(q['p75'])}, 90th pct {usd(q['p90'])}, "
        f"max {usd(q['max'])}.\n"
    )

    w(table(GROUP_HEAD, group_rows(g["size"], SIZE_ORDER)))
    top = next((x for x in g["size"] if x["group"] == SIZE_ORDER[-1]), None)
    if top and top["held"]:
        w(
            f"\nIn the largest bucket ({SIZE_ORDER[-1]}), {top['held_won']:.0f} of "
            f"{top['held']} positions held to settlement won against {top['held_implied']:.1f} "
            f"implied by price, and that bucket carries {usd(top['pnl'], True)} of P&L. Stake "
            'size was chosen before the outcome, so "conviction carried information" is a '
            "legitimate hypothesis, but it rests on a handful of positions and is reported as "
            "a hypothesis, not a finding.\n"
        )

    w("### By month of close\n")
    w(table(GROUP_HEAD, group_rows(sorted(g["month"], key=lambda x: x["group"]))))
    months = sorted(x["group"] for x in g["month"])
    busiest = max(g["month"], key=lambda x: x["n"])
    w(
        f"\n{busiest['n']} of {c['closed']} closed positions closed in {busiest['group']}. "
        f"Months missing between {months[0]} and {months[-1]} had no closed positions.\n"
    )

    w("### Closing-line value (cross-venue proxy)\n")
    w(
        "This pipeline has no price history for the Polymarket US book itself, so the "
        "closing benchmark is the last print before the scheduled start on Polymarket's "
        "*international* order book for the same game: a correlated but separate market. "
        "CLV is the backed side's closing price minus the entry price, in probability "
        "points. A position qualifies only if it is a single-game contract, every buy was "
        "before the start, and three independent checks agree on which reference outcome "
        "was backed: the outcome label matches exactly one name, the side matches title "
        "order, and the reference winner matches the US settlement.\n"
    )
    if cl["n"]:
        w(
            table(
                ["", "Value"],
                [
                    ["Qualifying positions (events)", f"{cl['n']} ({cl['events']})"],
                    [
                        "Mean CLV (95% CI, event-clustered)",
                        f"{pts(cl['mean']['point'], 2)} {ci(cl['mean'], pts)}",
                    ],
                    [
                        "Mean CLV after fees",
                        f"{pts(cl['mean_after_fees']['point'], 2)} {ci(cl['mean_after_fees'], pts)}",
                    ],
                    ["Share with positive CLV", f"{cl['share_positive']:.0%}"],
                ],
                "lr",
            )
        )
    w("\nWhy the other positions have no CLV:\n")
    w(table(["Reason", "Positions"], [[k, v] for k, v in cl["excluded"].items()]))
    inplay = sum(x["n"] for x in g["timing"] if x["group"] in ("in-play", "mixed"))
    w(
        f"\nThe pregame sample is small and the benchmark is a proxy, so this is weak "
        f"evidence either way. {inplay} of {c['closed']} closed positions were entered at or "
        "after the scheduled start, where there is no closing line. Forward-logging the US "
        "book's own pre-start price is the fix.\n"
    )

    # ---------------------------------------------------------------- checks
    w("## Integrity checks\n")
    w(
        "Every run asserts that the ledger is an exact partition of the fills, using "
        "`Decimal` arithmetic with no rounding:\n"
    )
    w(
        "```\n"
        f"sum of fill cash flows        {s['fill_cash_total']:>14}\n"
        f"+ settlement payouts          {s['payouts_total']:>14}\n"
        f"= realized P&L (closed)       {s['realized_pnl']:>14}\n"
        f"+ net cash in open positions  {s['open_net_cash']:>14}\n"
        "```\n"
    )
    sp = ck["settlement_pnl"]
    w(
        table(
            ["Cross-check against the exchange's own records", "Result"],
            [
                [
                    "Fill cash flow = exchange `trade.cost`",
                    f"{ck['fill_cost_match']} / {ck['fills']}",
                ],
                [
                    "Net shares at settlement = exchange pre-settlement position",
                    f"{ck['settled_qty_match']} / {ck['settled_markets']}",
                ],
                [
                    "Open positions = exchange open-positions snapshot",
                    f"{'match' if ck['open_match'] else 'MISMATCH'} ({ck['open_positions']} vs {ck['exchange_open_positions']})",
                ],
                [
                    "Gross volume per settled market = exchange counters",
                    f"{ck['settled_markets'] - len(ck['volume_gaps'])} / {ck['settled_markets']}",
                ],
                [
                    f"Settlement P&L ex fees, {sp['comparable']} markets without sells",
                    f"{sp['exact']} exact, {sp['rounding_4dp']} within the exchange's 4-dp rounding, {sp['booked_in_cost_field']} booked by the exchange in its `cost` field, {len(sp['other'])} other",
                ],
            ],
            "lr",
        )
    )
    if ck["volume_gaps"]:
        w(
            "\n**Volume gaps.** In these markets the exchange's position counters (YES terms) "
            "include executions that the activity feed did not return. The P&L the exchange "
            "had already realized on them before settlement is shown; it bounds what this "
            "ledger cannot see.\n"
        )
        w(
            table(
                [
                    "Market",
                    "Exchange bought / sold",
                    "Feed bought / sold",
                    "Exchange realized before settlement",
                ],
                [
                    [
                        v["market_slug"],
                        f"{num(v['exch_bought'], 0)} / {num(v['exch_sold'], 0)}",
                        f"{num(v['feed_bought'], 0)} / {num(v['feed_sold'], 0)}",
                        usd(v["exch_realized_before"], True),
                    ]
                    for v in ck["volume_gaps"]
                ],
                "lrrr",
            )
        )
        if sp["other"]:
            w(
                "\nThe settlement-P&L disagreements outside rounding and the `cost`-field "
                "quirk are: "
                + "; ".join(
                    f"`{o['market_slug']}` (ledger {usd(o['ledger'], True)}, exchange "
                    f"{usd(o['exchange'], True)})"
                    for o in sp["other"]
                )
                + ". They are in the volume-gap markets above and follow from the missing executions.\n"
            )
    w(
        "\nThe exchange also credited the account twice, for "
        f'{usd(credits.get("TRANSFER"))} in total, under the labels "System Issue" and '
        '"Balance reconciliation adjustment". Their cause is not in the records. They are '
        "excluded from trading P&L; if they compensated trading activity the feed omits, "
        "trading P&L here is understated by at most that amount.\n"
    )

    # ---------------------------------------------------------------- earlier
    w("## Relation to the earlier write-up\n")
    w(
        "The [polymarket-vegas-edge research note](https://github.com/crollila/polymarket-vegas-edge) "
        "analysed this same account from a 516-row export scraped from the web UI. That "
        'export has relative dates ("6mo ago"), no prices and no fees, so entry prices had '
        "to be inferred from payout ratios, and positions open at export were dropped. It "
        "reported 185 resolved positions, $12,615 deployed, +6.9% ROI with a 95% CI of "
        "[−3.5%, +17.8%], and three different P&L totals in different places "
        "(+$231.76, +$643 and +$866). "
        f"This ledger, built from the exchange's fill-level records, finds {c['closed']} closed "
        f"positions, {usd(s['capital_at_risk_closed'])} at risk, and "
        f"{usd(s['realized_pnl'], True)} ({pct(s['roi'])}). "
        + _earlier_comparison(g["league"])
        + " **Where the numbers differ, this document governs.**\n"
    )

    # ---------------------------------------------------------------- limits
    w("## Limitations\n")
    w(
        f"- One account, one venue, {len(g['month'])} months with closed positions and "
        f"{max(x['n'] for x in g['month'])} of {c['closed']} in a single month, mostly "
        "sports moneylines. This is not a long strategy track record.\n"
        "- No stored model probabilities, so edge at entry and model calibration cannot be "
        "measured. The calibration above concerns the *prices paid*, not a model.\n"
        "- The CLV benchmark is another venue's price, not the order book that was traded.\n"
        "- The activity feed omits a small amount of activity (see volume gaps). Its P&L "
        "effect is bounded by the exchange's own realized figures.\n"
        "- Drawdown is measured on realized P&L by close time. Intra-position mark-to-market "
        "swings are invisible without price history.\n"
        "- Positions in the same market on both sides are separate rows but the same event, "
        "and day clustering only partly captures cross-event correlation.\n"
    )

    # ---------------------------------------------------------------- repro
    w("## Reproduce\n")
    w(
        "From the committed, sanitized records (no account access needed):\n\n"
        "```bash\nuv run -m live.report          # rebuilds positions.csv, summary.json and this file\n"
        "uv run pytest tests/test_live_*.py\n```\n\n"
        "From the account itself (owner only; the raw file and the id salt stay outside the repo):\n\n"
        "```bash\n"
        "uv run -m live.ingest --raw /private/path/my_us_history.json\n"
        "uv run -m live.reference /path/to/games_year.jsonl   # optional: starts + CLV proxy\n"
        "uv run -m live.report\n"
        "```\n\n"
        "The raw input is the JSON from a read-only, authenticated pull of the account's "
        "`GET /v1/portfolio/activities` (all pages) and `GET /v1/portfolio/positions`. "
        "Only the account's own API key is needed. No private keys, seed phrases or wallet "
        "addresses are involved, since Polymarket US is account-based, and none are read "
        "or stored.\n"
    )
    w(
        "Privacy: published records contain public market identifiers, times, sizes, "
        "prices and fees. Exchange order, trade and transaction ids are replaced by "
        "salted HMACs. The counterparty side of every fill, withdrawal amounts and all "
        "free-text account descriptions are dropped at ingest.\n"
    )

    # ---------------------------------------------------------------- appendix
    w("## Appendix: every position\n")
    w(
        "Amounts rounded to the cent for display; exact values are in "
        "[`data/live/positions.csv`](data/live/positions.csv), together with fills, "
        "orders, quantities, exit and settlement prices, event start and its source, and "
        "CLV. Statuses: `settled` (held to resolution), `exited` (fully sold), `open` "
        "(unresolved at the pull, excluded from P&L).\n"
    )
    w(
        table(
            [
                "Position",
                "Entry (UTC)",
                "Market",
                "Side",
                "Type",
                "Timing",
                "Entry px",
                "Qty",
                "At risk",
                "Fees",
                "Exit / settle",
                "Status",
                "P&L",
                "Return",
            ],
            [
                [
                    f"`{r['position_id']}`",
                    minute(r["entry_utc"]),
                    _market(r),
                    r["side"],
                    r["order_types"]
                    .replace("LIMIT/", "LIMIT ")
                    .replace("IMMEDIATE_OR_CANCEL", "IOC")
                    .replace("+", ", "),
                    r["timing"],
                    num(r["entry_price"], 3),
                    num(r["qty_bought"], 2),
                    usd(r["capital_at_risk"]),
                    usd(r["fees"]),
                    _exit(r),
                    r["status"],
                    usd(r["realized_pnl"], True) if r["status"] != OPEN else "—",
                    pct(r["return"]) if r["status"] != OPEN else "—",
                ]
                for r in rows
            ],
            "llllllrrrrllrr",
        )
    )
    w("")
    return "\n".join(out)


def _earlier_comparison(leagues: list[dict]) -> str:
    """Compare this ledger with the earlier note's segment claims (quoted, not recomputed)."""
    by = {x["group"]: x for x in leagues}
    parts = []
    if "cbb" in by:
        parts.append(
            f"college basketball, which the note found to be −2.6% over 126 positions, is "
            f"{pct(by['cbb']['roi'])} over {by['cbb']['n']} here"
        )
    if "nfl" in by:
        parts.append(
            f"NFL, +100.4% over 11 positions there, is {pct(by['nfl']['roi'])} over "
            f"{by['nfl']['n']} here, still too few to mean much"
        )
    return ("On the segments the note highlighted: " + "; ".join(parts) + ".") if parts else ""


def _market(r: dict) -> str:
    if r["kind"] == "combo":
        return f"Combo ({r['league']}): {r['market'][:70]}{'…' if len(r['market']) > 70 else ''}"
    return f"{r['market']} → {r['outcome']}"


def _exit(r: dict) -> str:
    parts = []
    if r["exit_price"] is not None:
        parts.append(f"sold {num(r['exit_price'], 3)}")
    if r["status"] == SETTLED:
        parts.append(f"settled {num(r['settle_price'], 2)}")
    return "; ".join(parts) or "—"


def _brief(r: dict) -> list:
    return [
        f"`{r['position_id']}`",
        minute(r["entry_utc"]),
        _market(r),
        r["side"],
        num(r["entry_price"], 3),
        usd(r["capital_at_risk"]),
        usd(r["realized_pnl"], True),
    ]
